name: dt
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  meta: ^1.15.0

dev_dependencies:
  args: ^2.5.0
  benchmark_harness: ^2.2.2
  coverage: ^1.8.0
  oath: ^0.1.1
  path: ^1.9.0
  test: ^1.25.5
